web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.hoff.fr'
  environment:
    VIRTUAL_HOST: gitlab.hoff.fr
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.hoff.fr'
  ports:
    - '80:80'
    - '443:443'
    - '666:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'